/*
 * Copyright (c) 2025 OceanBase.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef OB_ALL_VIRTUAL_SQLITE_TABLES_H_
#define OB_ALL_VIRTUAL_SQLITE_TABLES_H_

// Auto-generated unified header for all SQLite virtual tables
// DO NOT EDIT THIS FILE MANUALLY

#include "observer/virtual_table/ob_virtual_table_scanner_iterator.h"
#include "share/storage/ob_sqlite_connection_pool.h"
#include "lib/container/ob_se_array.h"

namespace oceanbase
{
namespace observer
{

class ObAllVirtualSysParameter : public common::ObVirtualTableScannerIterator
{
public:
  ObAllVirtualSysParameter();
  virtual ~ObAllVirtualSysParameter();

  virtual int inner_open() override;
  virtual int inner_get_next_row(common::ObNewRow *&row) override;
  virtual void reset() override;

private:
  int fill_cells();
  int get_next_row_from_sqlite();

private:
  bool is_inited_;
  share::ObSQLiteConnectionGuard guard_;
  share::ObSQLiteStmt *stmt_;
  int64_t row_idx_;
  common::ObString name_;
  int64_t gmt_create_;
  int64_t gmt_modified_;
  common::ObString data_type_;
  common::ObString value_;
  common::ObString value_strict_;
  common::ObString info_;
  int64_t need_reboot_;
  common::ObString section_;
  common::ObString visible_level_;
  uint64_t config_version_;
  common::ObString scope_;
  common::ObString source_;
  common::ObString edit_level_;

  DISALLOW_COPY_AND_ASSIGN(ObAllVirtualSysParameter);
};

class ObAllVirtualDeadlockEventHistory : public common::ObVirtualTableScannerIterator
{
public:
  ObAllVirtualDeadlockEventHistory();
  virtual ~ObAllVirtualDeadlockEventHistory();

  virtual int inner_open() override;
  virtual int inner_get_next_row(common::ObNewRow *&row) override;
  virtual void reset() override;

private:
  int fill_cells();
  int get_next_row_from_sqlite();

private:
  bool is_inited_;
  share::ObSQLiteConnectionGuard guard_;
  share::ObSQLiteStmt *stmt_;
  int64_t row_idx_;
  int64_t event_id_;
  int64_t detector_id_;
  int64_t report_time_;
  int64_t cycle_idx_;
  int64_t cycle_size_;
  common::ObString role_;
  common::ObString priority_level_;
  int64_t priority_;
  int64_t create_time_;
  int64_t start_delay_;
  common::ObString module_;
  common::ObString visitor_;
  common::ObString object_;
  common::ObString extra_name1_;
  common::ObString extra_value1_;
  common::ObString extra_name2_;
  common::ObString extra_value2_;
  common::ObString extra_name3_;
  common::ObString extra_value3_;

  DISALLOW_COPY_AND_ASSIGN(ObAllVirtualDeadlockEventHistory);
};

class ObAllVirtualTabletMetaTable : public common::ObVirtualTableScannerIterator
{
public:
  ObAllVirtualTabletMetaTable();
  virtual ~ObAllVirtualTabletMetaTable();

  virtual int inner_open() override;
  virtual int inner_get_next_row(common::ObNewRow *&row) override;
  virtual void reset() override;

private:
  int fill_cells();
  int get_next_row_from_sqlite();

private:
  bool is_inited_;
  share::ObSQLiteConnectionGuard guard_;
  share::ObSQLiteStmt *stmt_;
  int64_t row_idx_;
  int64_t tablet_id_;
  int64_t gmt_create_;
  int64_t gmt_modified_;
  uint64_t compaction_scn_;
  int64_t data_size_;
  int64_t required_size_;
  uint64_t report_scn_;
  int64_t status_;

  DISALLOW_COPY_AND_ASSIGN(ObAllVirtualTabletMetaTable);
};

class ObAllVirtualTabletReplicaChecksum : public common::ObVirtualTableScannerIterator
{
public:
  ObAllVirtualTabletReplicaChecksum();
  virtual ~ObAllVirtualTabletReplicaChecksum();

  virtual int inner_open() override;
  virtual int inner_get_next_row(common::ObNewRow *&row) override;
  virtual void reset() override;

private:
  int fill_cells();
  int get_next_row_from_sqlite();

private:
  bool is_inited_;
  share::ObSQLiteConnectionGuard guard_;
  share::ObSQLiteStmt *stmt_;
  int64_t row_idx_;
  int64_t tablet_id_;
  uint64_t compaction_scn_;
  int64_t row_count_;
  int64_t data_checksum_;
  common::ObString column_checksums_;
  common::ObString b_column_checksums_;
  int64_t data_checksum_type_;
  uint64_t co_base_snapshot_version_;

  DISALLOW_COPY_AND_ASSIGN(ObAllVirtualTabletReplicaChecksum);
};

class ObAllVirtualZoneMergeInfo : public common::ObVirtualTableScannerIterator
{
public:
  ObAllVirtualZoneMergeInfo();
  virtual ~ObAllVirtualZoneMergeInfo();

  virtual int inner_open() override;
  virtual int inner_get_next_row(common::ObNewRow *&row) override;
  virtual void reset() override;

private:
  int fill_cells();
  int get_next_row_from_sqlite();

private:
  bool is_inited_;
  share::ObSQLiteConnectionGuard guard_;
  share::ObSQLiteStmt *stmt_;
  int64_t row_idx_;
  int64_t id_;
  uint64_t all_merged_scn_;
  uint64_t broadcast_scn_;
  uint64_t frozen_scn_;
  int64_t is_merging_;
  int64_t last_merged_time_;
  uint64_t last_merged_scn_;
  int64_t merge_start_time_;
  int64_t merge_status_;

  DISALLOW_COPY_AND_ASSIGN(ObAllVirtualZoneMergeInfo);
};

class ObAllVirtualMergeInfo : public common::ObVirtualTableScannerIterator
{
public:
  ObAllVirtualMergeInfo();
  virtual ~ObAllVirtualMergeInfo();

  virtual int inner_open() override;
  virtual int inner_get_next_row(common::ObNewRow *&row) override;
  virtual void reset() override;

private:
  int fill_cells();
  int get_next_row_from_sqlite();

private:
  bool is_inited_;
  share::ObSQLiteConnectionGuard guard_;
  share::ObSQLiteStmt *stmt_;
  int64_t row_idx_;
  int64_t id_;
  uint64_t frozen_scn_;
  uint64_t global_broadcast_scn_;
  int64_t is_merge_error_;
  uint64_t last_merged_scn_;
  int64_t merge_status_;
  int64_t error_type_;
  int64_t suspend_merging_;
  int64_t merge_start_time_;
  int64_t last_merged_time_;

  DISALLOW_COPY_AND_ASSIGN(ObAllVirtualMergeInfo);
};

class ObAllVirtualColumnChecksumErrorInfo : public common::ObVirtualTableScannerIterator
{
public:
  ObAllVirtualColumnChecksumErrorInfo();
  virtual ~ObAllVirtualColumnChecksumErrorInfo();

  virtual int inner_open() override;
  virtual int inner_get_next_row(common::ObNewRow *&row) override;
  virtual void reset() override;

private:
  int fill_cells();
  int get_next_row_from_sqlite();

private:
  bool is_inited_;
  share::ObSQLiteConnectionGuard guard_;
  share::ObSQLiteStmt *stmt_;
  int64_t row_idx_;
  uint64_t frozen_scn_;
  int64_t index_type_;
  int64_t data_table_id_;
  int64_t index_table_id_;
  int64_t data_tablet_id_;
  int64_t index_tablet_id_;
  int64_t column_id_;
  int64_t data_column_checksum_;
  int64_t index_column_checksum_;

  DISALLOW_COPY_AND_ASSIGN(ObAllVirtualColumnChecksumErrorInfo);
};

class ObAllVirtualReservedSnapshot : public common::ObVirtualTableScannerIterator
{
public:
  ObAllVirtualReservedSnapshot();
  virtual ~ObAllVirtualReservedSnapshot();

  virtual int inner_open() override;
  virtual int inner_get_next_row(common::ObNewRow *&row) override;
  virtual void reset() override;

private:
  int fill_cells();
  int get_next_row_from_sqlite();

private:
  bool is_inited_;
  share::ObSQLiteConnectionGuard guard_;
  share::ObSQLiteStmt *stmt_;
  int64_t row_idx_;
  int64_t snapshot_type_;
  int64_t create_time_;
  uint64_t snapshot_version_;
  int64_t status_;

  DISALLOW_COPY_AND_ASSIGN(ObAllVirtualReservedSnapshot);
};

class ObAllVirtualServerEventHistory : public common::ObVirtualTableScannerIterator
{
public:
  ObAllVirtualServerEventHistory();
  virtual ~ObAllVirtualServerEventHistory();

  virtual int inner_open() override;
  virtual int inner_get_next_row(common::ObNewRow *&row) override;
  virtual void reset() override;

private:
  int fill_cells();
  int get_next_row_from_sqlite();

private:
  bool is_inited_;
  share::ObSQLiteConnectionGuard guard_;
  share::ObSQLiteStmt *stmt_;
  int64_t row_idx_;
  int64_t gmt_create_;
  int64_t event_type_;
  common::ObString module_;
  common::ObString event_;
  common::ObString name1_;
  common::ObString value1_;
  common::ObString name2_;
  common::ObString value2_;
  common::ObString name3_;
  common::ObString value3_;
  common::ObString name4_;
  common::ObString value4_;
  common::ObString name5_;
  common::ObString value5_;
  common::ObString name6_;
  common::ObString value6_;
  common::ObString extra_info_;

  DISALLOW_COPY_AND_ASSIGN(ObAllVirtualServerEventHistory);
};

class ObAllVirtualEventHistory : public common::ObVirtualTableScannerIterator
{
public:
  ObAllVirtualEventHistory();
  virtual ~ObAllVirtualEventHistory();

  virtual int inner_open() override;
  virtual int inner_get_next_row(common::ObNewRow *&row) override;
  virtual void reset() override;

private:
  int fill_cells();
  int get_next_row_from_sqlite();

private:
  bool is_inited_;
  share::ObSQLiteConnectionGuard guard_;
  share::ObSQLiteStmt *stmt_;
  int64_t row_idx_;
  int64_t gmt_create_;
  common::ObString module_;
  common::ObString event_;
  common::ObString name1_;
  common::ObString value1_;
  common::ObString name2_;
  common::ObString value2_;
  common::ObString name3_;
  common::ObString value3_;
  common::ObString name4_;
  common::ObString value4_;
  common::ObString name5_;
  common::ObString value5_;
  common::ObString name6_;
  common::ObString value6_;
  common::ObString extra_info_;
  common::ObString trace_id_;
  int64_t cost_time_;
  int64_t ret_code_;
  common::ObString error_msg_;

  DISALLOW_COPY_AND_ASSIGN(ObAllVirtualEventHistory);
};

class ObAllVirtualRootserviceJob : public common::ObVirtualTableScannerIterator
{
public:
  ObAllVirtualRootserviceJob();
  virtual ~ObAllVirtualRootserviceJob();

  virtual int inner_open() override;
  virtual int inner_get_next_row(common::ObNewRow *&row) override;
  virtual void reset() override;

private:
  int fill_cells();
  int get_next_row_from_sqlite();

private:
  bool is_inited_;
  share::ObSQLiteConnectionGuard guard_;
  share::ObSQLiteStmt *stmt_;
  int64_t row_idx_;
  int64_t job_id_;
  int64_t gmt_create_;
  int64_t gmt_modified_;
  common::ObString job_type_;
  common::ObString job_status_;
  int64_t result_code_;

  DISALLOW_COPY_AND_ASSIGN(ObAllVirtualRootserviceJob);
};

} // namespace observer
} // namespace oceanbase

#endif /* OB_ALL_VIRTUAL_SQLITE_TABLES_H_ */
